# Generated by Django 4.2.16 on 2024-12-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar catálogo de Vehículos'), ('add_vehiculomodel', 'Can add Vehiculo model')]},
        ),
    ]
